<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/14.7.0/nouislider.min.css">';
echo '<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">';
echo '<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">';
echo '<link rel="stylesheet" href="styles.css">';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Calculator</title>';
echo '</head>';
echo '<body>';
echo '<div class = "upheader">';
echo '<a href="#" id="homeLink">';
echo '<img class ="logo" src="src/logo.jpg">';
echo '</a>';
echo '<div class = "phone_numbers">';
echo '<h3>8-800-100-5005</h3>';
echo '<h3>+7 (3452) 522-000</h3>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<header>';
echo '<div class="header">';
echo '<a style="border-left:none" href="#credit_cards">Кредитные карты</a>';
echo '<a href="#deposits">Вклады</a>';
echo '<a href="#debit_card">Дебетовая карта</a>';
echo '<a href="#insurance">Страхование</a>';
echo '<a href="#friends">Друзья</a>';
echo '<a href="#internet-bank">Интернет-банк</a>';
echo '</div>';
echo '</header>';
echo '';
echo '<div class="content">';
echo '<div id="breadcrumbs">';
echo '<a href="#" id="homeBreadcrumb">Главная</a>';
echo '</div>';
echo '';
echo '<form id="calculatorForm" class="calculator">';
echo '<h1>Калькулятор</h1>';
echo '<div class="wrapper">';
echo '<div class= "labels">';
echo '<label for="depositDate">Дата оформления вклада:</label>';
echo '<label for="depositAmount">Сумма вклада:</label>';
echo '<label for="depositTerm">Срок вклада:</label>';
echo '<label for="depositAdditional">Пополнение вклада:</label>';
echo '<label for="additionalAmount">Сумма пополнения вклада:</label>';
echo '</div>';
echo '';
echo '<div class = "inputs">';
echo '<div>';
echo '<input type="text" id="depositDate" name="depositDate" min="1900-01-01" placeholder="дд.мм.гггг">';
echo '</div>';
echo '';
echo '<div>';
echo '<input type="number" id="depositInput" name="depositAmount" min="1000" max="3000000">';
echo '</div>';
echo '';
echo '<div>';
echo '<select id="depositTerm" name="depositTerm">';
echo '<option value="1">1 год</option>';
echo '<option value="2">2 года</option>';
echo '<option value="3">3 года</option>';
echo '<option value="4">4 года</option>';
echo '<option value="5">5 лет</option>';
echo '</select>';
echo '</div>';
echo '';
echo '<div class="radios">';
echo '<input type="radio" id="additionalNo" name="depositAdditional" value="no" checked>';
echo '<label for="additionalNo">Нет</label>';
echo '<input type="radio" id="additionalYes" name="depositAdditional" value="yes">';
echo '<label for="additionalYes">Да</label>';
echo '</div>';
echo '';
echo '<div>';
echo '<input type="number" id="additionalInput" name="additionalAmount" min="1000" max="3000000">';
echo '</div>';
echo '</div>';
echo '<div class="sliders">';
echo '<div>';
echo '<div id="depositSlider"></div>';
echo '<div class="spans">';
echo '<span id="leftLabel">1 тыс. руб.</span>';
echo '<span id="rightLabel">3 000 000</span>';
echo '</div>';
echo '</div>';
echo '';
echo '<div>';
echo '<div id="additionalSlider"></div>';
echo '<div class="spans">';
echo '<span id="leftLabel">1 тыс. руб.</span>';
echo '<span id="rightLabel">3 000 000</span>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '<div>';
echo '<button type="submit">Рассчитать</button>';
echo '<label id="resultLabel">Результат: </label>';
echo '<label id="result"></label>';
echo '</div>';
echo '</form>';
echo '';
echo '</div>';
echo '';
echo '<footer>';
echo '<p>Кредитные карты</p>';
echo '<p>Вклады </p>';
echo '<p>Дебетовая карта</p>';
echo '<p>Страхование </p>';
echo '<p>Друзья</p>';
echo '<p>Интернет-банк</p>';
echo '</footer>';
echo '';
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/14.7.0/nouislider.min.js"></script>';
echo '<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>';
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>';
echo '<script src="script.js"></script>';
echo '';
echo '';
echo '</body>';
echo '</html>';